#!/bin/bash

# Exit on first failing command.
set -e
# Echo commands to console.
set -x

IMAGE_NAME="demo-app-image"
CONTAINER_NAME="demo-app"

docker version

docker build \
  --tag "$IMAGE_NAME" \
  .

# Clear any previous container.
docker rm -f "$CONTAINER_NAME" &> /dev/null || true

docker run \
  --tty \
  --detach \
  --publish 80:5000 \
  --name "$CONTAINER_NAME" \
  "$IMAGE_NAME"

# Give the container a little time to start up.
sleep 6

curl \
  --retry 15 \
  --retry-delay 2 \
  --fail \
  "http://localhost/" > /dev/null

echo "App is serving!"
